### ISSUE TITLE
networkEndOfLifeDate to expire at the end of December 2021

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/networks#87]
Currently in the [genesis file](https://github.com/vegaprotocol/networks/blob/master/mainnet1/genesis.json) for `mainnet1` the `networkEndOfLifeDate` parameter is set to expire at the end of 2021:

`"network.checkpoint.networkEndOfLifeDate": "2021-12-31T23:59:00Z"`

**Comment by joe-bowman** [comment]
Comment from @jeremyletang on Discord:

> OK, so about this one. This is not an actual issue. This network parameter is too basically decide when the network would be expected to shut down. For now it's only indicative and will not take any action in the network. In the future we would expect this parameter to stop people to do things like e.g: withdrawal if they are in a range of time to close from the expected shutdown of the network for example.

**Comment by joe-bowman** [comment]
Tl:dr is that the value is not impactful at present, and can be ignored.
